// <auto-generated />
using System;
using EduCore.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EduCore.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260715174915_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EduCore.Domain.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Hours")
                        .HasColumnType("int")
                        .HasColumnName("Hours");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("InstructorId");

                    b.ToTable("Course", null, t =>
                        {
                            t.HasCheckConstraint("CK_Course_Hours_Min", "[Hours] > 0");

                            t.HasCheckConstraint("CK_Course_Price_Min", "[Price] >=0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Description = "Learn C# from scratch",
                            Hours = 40,
                            InstructorId = 1,
                            Price = 1500.00m,
                            Title = "C# Basics"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            Description = "Build web apps",
                            Hours = 60,
                            InstructorId = 2,
                            Price = 2500.00m,
                            Title = "ASP.NET Core"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 2,
                            Description = "Intro to ML",
                            Hours = 50,
                            InstructorId = 3,
                            Price = 3000.00m,
                            Title = "Machine Learning"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 2,
                            Description = "Neural networks",
                            Hours = 70,
                            InstructorId = 4,
                            Price = 3500.00m,
                            Title = "Deep Learning"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 3,
                            Description = "Penetration testing",
                            Hours = 45,
                            InstructorId = 5,
                            Price = 2800.00m,
                            Title = "Ethical Hacking"
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 3,
                            Description = "Securing networks",
                            Hours = 55,
                            InstructorId = 13,
                            Price = 2600.00m,
                            Title = "Network Security"
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 4,
                            Description = "Marketing principles",
                            Hours = 30,
                            InstructorId = 6,
                            Price = 1000.00m,
                            Title = "Marketing 101"
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 4,
                            Description = "PMP basics",
                            Hours = 40,
                            InstructorId = 7,
                            Price = 1800.00m,
                            Title = "Project Management"
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 5,
                            Description = "Design interfaces",
                            Hours = 35,
                            InstructorId = 8,
                            Price = 1200.00m,
                            Title = "UI/UX Fundamentals"
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 6,
                            Description = "Pandas & NumPy",
                            Hours = 50,
                            InstructorId = 9,
                            Price = 2200.00m,
                            Title = "Python for Data Science"
                        },
                        new
                        {
                            Id = 11,
                            DepartmentId = 7,
                            Description = "Intermediate conversation",
                            Hours = 40,
                            InstructorId = 10,
                            Price = 800.00m,
                            Title = "English B2"
                        },
                        new
                        {
                            Id = 12,
                            DepartmentId = 1,
                            Description = "Algorithms in C#",
                            Hours = 45,
                            InstructorId = 11,
                            Price = 1700.00m,
                            Title = "Data Structures"
                        },
                        new
                        {
                            Id = 13,
                            DepartmentId = 2,
                            Description = "Image processing",
                            Hours = 60,
                            InstructorId = 12,
                            Price = 3200.00m,
                            Title = "Computer Vision"
                        },
                        new
                        {
                            Id = 14,
                            DepartmentId = 3,
                            Description = "Encryption techniques",
                            Hours = 50,
                            InstructorId = 5,
                            Price = 2900.00m,
                            Title = "Cryptography"
                        },
                        new
                        {
                            Id = 15,
                            DepartmentId = 5,
                            Description = "Photoshop & Illustrator",
                            Hours = 40,
                            InstructorId = 14,
                            Price = 1400.00m,
                            Title = "Graphic Design"
                        },
                        new
                        {
                            Id = 16,
                            DepartmentId = 6,
                            Description = "Hadoop & Spark",
                            Hours = 65,
                            InstructorId = 15,
                            Price = 3100.00m,
                            Title = "Big Data"
                        },
                        new
                        {
                            Id = 17,
                            DepartmentId = 7,
                            Description = "Beginner Spanish",
                            Hours = 30,
                            InstructorId = 10,
                            Price = 700.00m,
                            Title = "Spanish A1"
                        },
                        new
                        {
                            Id = 18,
                            DepartmentId = 4,
                            Description = "Human resources basics",
                            Hours = 35,
                            InstructorId = 6,
                            Price = 1100.00m,
                            Title = "HR Management"
                        },
                        new
                        {
                            Id = 19,
                            DepartmentId = 5,
                            Description = "HTML, CSS, JS",
                            Hours = 45,
                            InstructorId = 8,
                            Price = 1300.00m,
                            Title = "Web Design"
                        },
                        new
                        {
                            Id = 20,
                            DepartmentId = 1,
                            Description = "AWS & Azure",
                            Hours = 55,
                            InstructorId = 2,
                            Price = 2700.00m,
                            Title = "Cloud Computing"
                        });
                });

            modelBuilder.Entity("EduCore.Domain.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Department", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Software Development & Programming",
                            Name = "Computer Science"
                        },
                        new
                        {
                            Id = 2,
                            Description = "AI & Machine Learning",
                            Name = "Artificial Intelligence"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Security & Networking",
                            Name = "Cyber Security"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Business Administration",
                            Name = "Business"
                        },
                        new
                        {
                            Id = 5,
                            Description = "UI/UX & Graphic Design",
                            Name = "Design"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Data Analysis and Big Data",
                            Name = "Data Science"
                        },
                        new
                        {
                            Id = 7,
                            Description = "English, Spanish, and German",
                            Name = "Languages"
                        });
                });

            modelBuilder.Entity("EduCore.Domain.Entities.Enrollment", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EnrollDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("Progress")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("Enrollment", null, t =>
                        {
                            t.HasCheckConstraint("CK_Enrollment_Progress_Range", "[Progress] >=0 AND [Progress] <=100");
                        });

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            CourseId = 1,
                            EnrollDate = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 100,
                            Status = "Completed"
                        },
                        new
                        {
                            StudentId = 1,
                            CourseId = 2,
                            EnrollDate = new DateTime(2023, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 40,
                            Status = "Active"
                        },
                        new
                        {
                            StudentId = 2,
                            CourseId = 3,
                            EnrollDate = new DateTime(2023, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 80,
                            Status = "Active"
                        },
                        new
                        {
                            StudentId = 2,
                            CourseId = 4,
                            EnrollDate = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 0,
                            Status = "Pending"
                        },
                        new
                        {
                            StudentId = 3,
                            CourseId = 5,
                            EnrollDate = new DateTime(2022, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 100,
                            Status = "Completed"
                        },
                        new
                        {
                            StudentId = 4,
                            CourseId = 1,
                            EnrollDate = new DateTime(2023, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 50,
                            Status = "Active"
                        },
                        new
                        {
                            StudentId = 4,
                            CourseId = 9,
                            EnrollDate = new DateTime(2023, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 10,
                            Status = "Active"
                        },
                        new
                        {
                            StudentId = 5,
                            CourseId = 8,
                            EnrollDate = new DateTime(2021, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 100,
                            Status = "Completed"
                        },
                        new
                        {
                            StudentId = 5,
                            CourseId = 7,
                            EnrollDate = new DateTime(2021, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 100,
                            Status = "Completed"
                        },
                        new
                        {
                            StudentId = 6,
                            CourseId = 11,
                            EnrollDate = new DateTime(2023, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 5,
                            Status = "Active"
                        },
                        new
                        {
                            StudentId = 7,
                            CourseId = 10,
                            EnrollDate = new DateTime(2022, 12, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 90,
                            Status = "Active"
                        },
                        new
                        {
                            StudentId = 8,
                            CourseId = 2,
                            EnrollDate = new DateTime(2023, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 30,
                            Status = "Cancelled"
                        },
                        new
                        {
                            StudentId = 9,
                            CourseId = 5,
                            EnrollDate = new DateTime(2020, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 100,
                            Status = "Completed"
                        },
                        new
                        {
                            StudentId = 9,
                            CourseId = 6,
                            EnrollDate = new DateTime(2021, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 100,
                            Status = "Completed"
                        },
                        new
                        {
                            StudentId = 10,
                            CourseId = 12,
                            EnrollDate = new DateTime(2023, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 20,
                            Status = "Active"
                        },
                        new
                        {
                            StudentId = 11,
                            CourseId = 13,
                            EnrollDate = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 60,
                            Status = "Active"
                        },
                        new
                        {
                            StudentId = 12,
                            CourseId = 14,
                            EnrollDate = new DateTime(2023, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 45,
                            Status = "Active"
                        },
                        new
                        {
                            StudentId = 13,
                            CourseId = 15,
                            EnrollDate = new DateTime(2023, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 100,
                            Status = "Completed"
                        },
                        new
                        {
                            StudentId = 14,
                            CourseId = 16,
                            EnrollDate = new DateTime(2023, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 75,
                            Status = "Active"
                        },
                        new
                        {
                            StudentId = 15,
                            CourseId = 17,
                            EnrollDate = new DateTime(2023, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 10,
                            Status = "Active"
                        },
                        new
                        {
                            StudentId = 16,
                            CourseId = 18,
                            EnrollDate = new DateTime(2022, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 100,
                            Status = "Completed"
                        },
                        new
                        {
                            StudentId = 17,
                            CourseId = 19,
                            EnrollDate = new DateTime(2023, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 35,
                            Status = "Active"
                        },
                        new
                        {
                            StudentId = 18,
                            CourseId = 20,
                            EnrollDate = new DateTime(2023, 8, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 55,
                            Status = "Active"
                        },
                        new
                        {
                            StudentId = 19,
                            CourseId = 1,
                            EnrollDate = new DateTime(2023, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 0,
                            Status = "Pending"
                        },
                        new
                        {
                            StudentId = 20,
                            CourseId = 2,
                            EnrollDate = new DateTime(2023, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 0,
                            Status = "Pending"
                        },
                        new
                        {
                            StudentId = 21,
                            CourseId = 3,
                            EnrollDate = new DateTime(2022, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 100,
                            Status = "Completed"
                        },
                        new
                        {
                            StudentId = 22,
                            CourseId = 4,
                            EnrollDate = new DateTime(2023, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 85,
                            Status = "Active"
                        },
                        new
                        {
                            StudentId = 23,
                            CourseId = 5,
                            EnrollDate = new DateTime(2023, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 40,
                            Status = "Active"
                        },
                        new
                        {
                            StudentId = 24,
                            CourseId = 6,
                            EnrollDate = new DateTime(2023, 4, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 25,
                            Status = "Active"
                        },
                        new
                        {
                            StudentId = 25,
                            CourseId = 7,
                            EnrollDate = new DateTime(2022, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 100,
                            Status = "Completed"
                        },
                        new
                        {
                            StudentId = 26,
                            CourseId = 8,
                            EnrollDate = new DateTime(2023, 6, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 50,
                            Status = "Active"
                        },
                        new
                        {
                            StudentId = 27,
                            CourseId = 9,
                            EnrollDate = new DateTime(2023, 7, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 15,
                            Status = "Active"
                        },
                        new
                        {
                            StudentId = 28,
                            CourseId = 10,
                            EnrollDate = new DateTime(2022, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 100,
                            Status = "Completed"
                        },
                        new
                        {
                            StudentId = 29,
                            CourseId = 11,
                            EnrollDate = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 0,
                            Status = "Cancelled"
                        },
                        new
                        {
                            StudentId = 30,
                            CourseId = 12,
                            EnrollDate = new DateTime(2023, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Progress = 5,
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("EduCore.Domain.Entities.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Instructor", null, t =>
                        {
                            t.HasCheckConstraint("CK_Instructor_Salary_Min", "[Salary] > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Email = "ahmed.ali@univ.edu",
                            FullName = "Ahmed Ali",
                            HireDate = new DateTime(2015, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "01011110001",
                            Salary = 12000.00m
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            Email = "sara.hassan@univ.edu",
                            FullName = "Sara Hassan",
                            HireDate = new DateTime(2016, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "01122220002",
                            Salary = 13500.50m
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 2,
                            Email = "m.tarek@univ.edu",
                            FullName = "Mohamed Tarek",
                            HireDate = new DateTime(2018, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "01233330003",
                            Salary = 15000.00m
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 2,
                            Email = "nour.y@univ.edu",
                            FullName = "Nour Youssef",
                            HireDate = new DateTime(2019, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "01544440004",
                            Salary = 14200.00m
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 3,
                            Email = "omar.khaled@univ.edu",
                            FullName = "Omar Khaled",
                            HireDate = new DateTime(2014, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "01055550005",
                            Salary = 16000.00m
                        },
                        new
                        {
                            Id = 6,
                            DepartmentId = 4,
                            Email = "mona.i@univ.edu",
                            FullName = "Mona Ibrahim",
                            HireDate = new DateTime(2020, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "01166660006",
                            Salary = 11000.00m
                        },
                        new
                        {
                            Id = 7,
                            DepartmentId = 4,
                            Email = "hany.said@univ.edu",
                            FullName = "Hany Said",
                            HireDate = new DateTime(2021, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "01277770007",
                            Salary = 11500.00m
                        },
                        new
                        {
                            Id = 8,
                            DepartmentId = 5,
                            Email = "dina.adel@univ.edu",
                            FullName = "Dina Adel",
                            HireDate = new DateTime(2017, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "01588880008",
                            Salary = 12500.00m
                        },
                        new
                        {
                            Id = 9,
                            DepartmentId = 6,
                            Email = "tarek.z@univ.edu",
                            FullName = "Tarek Ziad",
                            HireDate = new DateTime(2016, 10, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "01099990009",
                            Salary = 14000.00m
                        },
                        new
                        {
                            Id = 10,
                            DepartmentId = 7,
                            Email = "salma.f@univ.edu",
                            FullName = "Salma Farouk",
                            HireDate = new DateTime(2022, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "01100000010",
                            Salary = 9500.00m
                        },
                        new
                        {
                            Id = 11,
                            DepartmentId = 1,
                            Email = "yassin.m@univ.edu",
                            FullName = "Yassin Mahmoud",
                            HireDate = new DateTime(2019, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "01211110011",
                            Salary = 13000.00m
                        },
                        new
                        {
                            Id = 12,
                            DepartmentId = 2,
                            Email = "laila.k@univ.edu",
                            FullName = "Laila Kamal",
                            HireDate = new DateTime(2013, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "01522220012",
                            Salary = 17000.00m
                        },
                        new
                        {
                            Id = 13,
                            DepartmentId = 3,
                            Email = "ibrahim.m@univ.edu",
                            FullName = "Ibrahim Mostafa",
                            HireDate = new DateTime(2018, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "01033330013",
                            Salary = 14500.00m
                        },
                        new
                        {
                            Id = 14,
                            DepartmentId = 5,
                            Email = "yasmine.f@univ.edu",
                            FullName = "Yasmine Fathy",
                            HireDate = new DateTime(2021, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "01144440014",
                            Salary = 10500.00m
                        },
                        new
                        {
                            Id = 15,
                            DepartmentId = 6,
                            Email = "kareem.w@univ.edu",
                            FullName = "Kareem Wael",
                            HireDate = new DateTime(2015, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "01255550015",
                            Salary = 15500.00m
                        });
                });

            modelBuilder.Entity("EduCore.Domain.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("RegisterDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GetDate()");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Phone")
                        .IsUnique();

                    b.ToTable("Student", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthDate = new DateTime(2000, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "youssef.g@example.com",
                            FullName = "Youssef Gamal",
                            Phone = "01012345671",
                            RegisterDate = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            BirthDate = new DateTime(2001, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "aya.m@example.com",
                            FullName = "Aya Mahmoud",
                            Phone = "01123456782",
                            RegisterDate = new DateTime(2023, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            BirthDate = new DateTime(1999, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mahmoud.s@example.com",
                            FullName = "Mahmoud Salah",
                            Phone = "01234567893",
                            RegisterDate = new DateTime(2022, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            BirthDate = new DateTime(2002, 3, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fatma.s@example.com",
                            FullName = "Fatma Said",
                            Phone = "01545678904",
                            RegisterDate = new DateTime(2023, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            BirthDate = new DateTime(1998, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "karim.h@example.com",
                            FullName = "Karim Hassan",
                            Phone = "01056789015",
                            RegisterDate = new DateTime(2021, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            BirthDate = new DateTime(2003, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nada.t@example.com",
                            FullName = "Nada Tarek",
                            Phone = "01167890126",
                            RegisterDate = new DateTime(2023, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            BirthDate = new DateTime(2000, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "amr.z@example.com",
                            FullName = "Amr Zaki",
                            Phone = "01278901237",
                            RegisterDate = new DateTime(2022, 12, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            BirthDate = new DateTime(2001, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hoda.a@example.com",
                            FullName = "Hoda Ali",
                            Phone = "01589012348",
                            RegisterDate = new DateTime(2023, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            BirthDate = new DateTime(1997, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mostafa.k@example.com",
                            FullName = "Mostafa Kamal",
                            Phone = "01090123459",
                            RegisterDate = new DateTime(2020, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            BirthDate = new DateTime(2002, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rana.o@example.com",
                            FullName = "Rana Othman",
                            Phone = "01101234560",
                            RegisterDate = new DateTime(2023, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            BirthDate = new DateTime(1999, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "omar.f@example.com",
                            FullName = "Omar Fathy",
                            Phone = "01212345671",
                            RegisterDate = new DateTime(2022, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            BirthDate = new DateTime(2001, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "salma.a@example.com",
                            FullName = "Salma Adel",
                            Phone = "01523456782",
                            RegisterDate = new DateTime(2023, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            BirthDate = new DateTime(1998, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ahmed.m@example.com",
                            FullName = "Ahmed Mostafa",
                            Phone = "01034567893",
                            RegisterDate = new DateTime(2021, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            BirthDate = new DateTime(2003, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mona.i@example.com",
                            FullName = "Mona Ibrahim",
                            Phone = "01145678904",
                            RegisterDate = new DateTime(2023, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            BirthDate = new DateTime(2000, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "tarek.k@example.com",
                            FullName = "Tarek Khaled",
                            Phone = "01256789015",
                            RegisterDate = new DateTime(2022, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            BirthDate = new DateTime(1999, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dina.y@example.com",
                            FullName = "Dina Youssef",
                            Phone = "01567890126",
                            RegisterDate = new DateTime(2021, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            BirthDate = new DateTime(2002, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hassan.w@example.com",
                            FullName = "Hassan Wael",
                            Phone = "01078901237",
                            RegisterDate = new DateTime(2023, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            BirthDate = new DateTime(2001, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nour.f@example.com",
                            FullName = "Nour Farouk",
                            Phone = "01189012348",
                            RegisterDate = new DateTime(2022, 5, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            BirthDate = new DateTime(1998, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ziad.z@example.com",
                            FullName = "Ziad Ziad",
                            Phone = "01290123459",
                            RegisterDate = new DateTime(2020, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            BirthDate = new DateTime(2000, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "yasmine.s@example.com",
                            FullName = "Yasmine Samy",
                            Phone = "01501234560",
                            RegisterDate = new DateTime(2023, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 21,
                            BirthDate = new DateTime(1999, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ibrahim.g@example.com",
                            FullName = "Ibrahim Gamal",
                            Phone = "01011122233",
                            RegisterDate = new DateTime(2022, 7, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 22,
                            BirthDate = new DateTime(2003, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "laila.m@example.com",
                            FullName = "Laila Mahmoud",
                            Phone = "01122233344",
                            RegisterDate = new DateTime(2023, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 23,
                            BirthDate = new DateTime(1997, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kareem.s@example.com",
                            FullName = "Kareem Salah",
                            Phone = "01233344455",
                            RegisterDate = new DateTime(2020, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 24,
                            BirthDate = new DateTime(2001, 3, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sara.s@example.com",
                            FullName = "Sara Said",
                            Phone = "01544455566",
                            RegisterDate = new DateTime(2022, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 25,
                            BirthDate = new DateTime(1998, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ali.h@example.com",
                            FullName = "Ali Hassan",
                            Phone = "01055566677",
                            RegisterDate = new DateTime(2021, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 26,
                            BirthDate = new DateTime(2002, 1, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "habiba.t@example.com",
                            FullName = "Habiba Tarek",
                            Phone = "01166677788",
                            RegisterDate = new DateTime(2023, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 27,
                            BirthDate = new DateTime(2000, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "wael.z@example.com",
                            FullName = "Wael Zaki",
                            Phone = "01277788899",
                            RegisterDate = new DateTime(2022, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 28,
                            BirthDate = new DateTime(1999, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "farah.a@example.com",
                            FullName = "Farah Ali",
                            Phone = "01588899900",
                            RegisterDate = new DateTime(2021, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 29,
                            BirthDate = new DateTime(2001, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "saad.k@example.com",
                            FullName = "Saad Kamal",
                            Phone = "01099900011",
                            RegisterDate = new DateTime(2023, 3, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 30,
                            BirthDate = new DateTime(2003, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "malak.o@example.com",
                            FullName = "Malak Othman",
                            Phone = "01100011122",
                            RegisterDate = new DateTime(2023, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("EduCore.Domain.Entities.Course", b =>
                {
                    b.HasOne("EduCore.Domain.Entities.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EduCore.Domain.Entities.Instructor", "Instructor")
                        .WithMany("Courses")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("EduCore.Domain.Entities.Enrollment", b =>
                {
                    b.HasOne("EduCore.Domain.Entities.Course", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EduCore.Domain.Entities.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EduCore.Domain.Entities.Instructor", b =>
                {
                    b.HasOne("EduCore.Domain.Entities.Department", "Department")
                        .WithMany("Instructors")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("EduCore.Domain.Entities.Course", b =>
                {
                    b.Navigation("Enrollments");
                });

            modelBuilder.Entity("EduCore.Domain.Entities.Department", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("Instructors");
                });

            modelBuilder.Entity("EduCore.Domain.Entities.Instructor", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("EduCore.Domain.Entities.Student", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
